apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: indexer-cronjob
spec:
  schedule: "0 * * * *"  # This cron job runs every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: indexer
            image: your-docker-image:latest  # Replace with your actual image
            args:
            - python
            - -m
            - src.indexer.job  # Adjust the module path as necessary
          restartPolicy: OnFailure
